### ISSUE TITLE
Compatibility Inquiry: bitarray 1.3.0  with Ruby 3.3.0 in Linux

### ISSUE THREAD

**Issue by sydverisk** [peterc/bitarray#18]
Hi,

I'm seeking confirmation regarding the compatibility of the bitarray 1.3.0  with the recently released Ruby 3.3.0 (December 25, 2023).

While I reviewed the gem's documentation on RubyGems(https://rubygems.org/gems/bitarray) and github(https://github.com/peterc/bitarray) it only specifies a minimum required Ruby version of > 0. Unfortunately, I haven't found any explicit confirmation on compatibility with newer versions like 3.3.0.

Given your expertise in this area, could you offer any insights or leads on this matter? Any information you can provide would be greatly appreciated.

Thank you for your time and assistance!

**Comment by peterc** [comment]
I have _not_ tested on Linux specifically, but have tested with Ruby 3.0 and 3.3 on macOS and all is fine. There are no platform specific features, however.

**Comment by peterc** [comment]
I have updated the README with this information, however.

**Comment by sydverisk** [comment]
Thanks @peterc for the update, much appreciated!
