### ISSUE TITLE
Issue when setting 0 bit to 0

### ISSUE THREAD

**Issue by tdeo** [peterc/bitarray#7]
The following behaviour seems incorrect:
```
2.4.3 :100 > z = BitArray.new(12)
 => #<BitArray:0x00007fa023079d18 @size=12, @field="\u0000\u0000">
2.4.3 :101 > z[3]
 => 0
2.4.3 :102 > z[3] = 0
 => 0
2.4.3 :103 > z[3]
 => 1
2.4.3 :104 > z[3] = 0
 => 0
2.4.3 :105 > z[3]
 => 0
2.4.3 :106 > z[3] = 0
 => 0
2.4.3 :107 > z[3]
 => 1
```

Setting to `0` should be done with `@field.setbyte(position >> 3, @field.getbyte(position >> 3) & ~(1 << (position % 8)))`

**Comment by m1lt0n** [comment]
@tdeo Ran into this issue, too and created a slightly different PR. Mentioning here in order to allow the maintainer of the gem close one of the two and merge the other one: #10
